### ISSUE TITLE
P2-5

### ISSUE THREAD

**Issue by PaskaFilip** [julianrybarczyk/Webowe_Proj2#5]
_Oczekuje na P2-III_
- Zaimplementuj w osobnym pliku
pythonowym klasę, która będzie
odpowiedzialna za przechowywanie
sesji użytkownika.

**Comment by julianrybarczyk** [comment]
[Metody do klasy](https://github.com/julianrybarczyk/Webowe_Proj2/issues/3#issuecomment-1825738332)

**Comment by julianrybarczyk** [comment]
Dorzuć jeszcze metody dla id użytkownika (userId)
